
development: &development
    db:
        adapter: mysql
        host: localhost
        username: root
        password: 238457
        database: test
    search:
        host: http://localhost:8983/solr/mapper_development/
    broker:
        host: localhost:1234
        queue_name: rabbit.mapper
    concurrency: 
        pool_size: 4
        iterator_size: 4
    extensions: 
        - xlsx
production: 
    db:
        adapter: mysql
        host: localhost
        username: root
        password: 238457
        database: test
    search:
        host: http://localhost:8983/solr/mapper_production/
    broker:
        host: localhost:1234
        queue_name: rabbit.mapper
    concurrency: 
        pool_size: 4
        iterator_size: 4
    extensions: 
        - xlsx
    