---
development:
  db:
    storage:
      adapter: em_mysql2
      active-adapter: mysql2
      host: localhost
      username: root
      password: '238457'
      database: storage
    shop:
      adapter: em_mysql2
      active-adapter: mysql2
      host: localhost
      username: root
      password: '238457'
      database: shop
  search:
    host: http://localhost:8983/solr/development/
  broker:
    host: localhost:1234
    queue-name: rabbit.mapper
  concurrency:
    iterator-size: '4'
    pool-size: '4'
  extensions: xlsx,csv
  dir: prices
production:
  db:
    storage:
      adapter: em_mysql2
      active-adapter: mysql2
      host: localhost
      username: root
      password: password
      database: storage
    shop:
      adapter: em_mysql2
      active-adapter: mysql2
      host: localhost
      username: root
      password: password
      database: shop
  search:
    host: http://localhost:8983/solr/mapper_development/
  broker:
    host: localhost:1234
    queue-name: rabbit.mapper
  concurrency:
    pool-size: 4
    iterator-size: 4
  extensions: csv,xlsx
  dir: prices
